apiVersion: v1
kind: ConfigMap
metadata:
  name: xeno-fde-backend-config
  namespace: xeno-fde-backend
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
